let data = {
  EN: {
    pageTitle: 'Add profile',
    pageTitle2: 'Update profile',
    nameCol: 'Name business',
    addFile: 'Add Files',
    selectList: 'Select list',
    allStaff: 'All staff',
    mainHandler: 'main handler',
    previousStep: 'Previous Step',
    finishCol: 'Finish',
    enterInfomation: '1.Infomation file cabinet',
    relatedList: '2.Related List',
    nextStep: 'Next Step',
  },
  VN: {
    nextStep: 'Bước tiếp theo',
    pageTitle: 'Thêm hồ sơ cá nhân',
    pageTitle2: 'Sửa hồ sơ cá nhân',
    nameCol: 'Tên hồ sơ',
    addFile: 'Thêm file',
    selectList: 'Lựa chọn danh sách từ',
    allStaff: 'Tất cả nhân viên',
    mainHanler: 'Người xử lý chính',
    previousStep: 'Quay lại',
    finishCol: 'Kết thúc',
    enterInfomation: '1.Nhập dữ liệu hồ sơ',
    relatedList: '2.Danh sách được chia sẻ',
  },
};
export default data;
