import { CalendarComponent } from './../../utilities/calendar/calendar.component';
let data = {
  EN: {
    pageTitle: 'Event list',
    newFile: 'New event',
    itemsPerPage: 'Number of items per page',
    nextBtn: 'Next',
    previousBtn: 'Previous',
    dateCol: 'Date',
    timeCol: 'Time',
    descriptionCol: 'Description',
    locationCol: 'Location',
    to: 'to',
    verify: 'Verified',
    unverify: 'Unverify',
    newBtn: 'Add Event',
    apBtn: 'Approved Event',
    canBtn: 'Cancel Event',
    deBtn: 'Delete Event',
    printBtn: 'Print Event',
  },
  VN: {
    pageTitle: 'Lịch tuần',
    newFile: 'Thêm lịch mới',
    itemsPerPage: 'Số lượng thư mục mỗi trang',
    nextBtn: 'Trang sau',
    previousBtn: 'Trang trước',
    dateCol: 'Ngày',
    timeCol: 'Giờ',
    descriptionCol: 'Nội dung',
    locationCol: 'Địa điểm',
    to: 'đến',
    verify: 'Đã duyệt',
    unverify: 'Chưa duyệt',
    newBtn: 'Thêm Lịch',
    apBtn: 'Phê Duyệt',
    canBtn: 'Hủy Lịch',
    deBtn: 'Xóa Lịch',
    printBtn: 'In Lịch',
  },
};
export default data;
