let data = {
  EN: {
    pageTitle: 'New Personal Calendar',
    pageTitle2: 'Update Personal Calendar',
    startCol: 'Start',
    theEnd: 'End',
    contentCol: 'Content',
    locationCol: 'location',
    addFiles: 'Add files',
    nextCol: 'Next',
    selectList: 'Select list',
    allStaff: 'all staff',
    mainHandler: 'main handler',
    previousStep: 'Previous Step',
    finishCol: 'Finish',
    enterInfomation: '1.Infomation calendar',
    relatedList: '2.Related List',
  },
  VN: {
    pageTitle: 'Thêm Lịch Cá Nhân',
    pageTitle2: 'Sửa Lịch Cá Nhân',
    startCol: 'Bắt đầu',
    theEnd: 'Kết thúc',
    contentCol: 'Nội dung',
    locationCal: 'Địa điểm',
    addFiles: 'Thêm file',
    nextCol: 'Tiếp tục',
    selectList: 'Lựa chọn danh sách từ',
    allStaff: 'Tất cả nhân viên',
    mainHanler: 'Người xử lý chính',
    previousStep: 'Quay lại',
    finishCol: 'Kết thúc',
    enterInfomation: '1.Nhập thông tin lịch',
    relatedList: 'Chia sẻ',
  },
};
export default data;
